[module]
[module.hugoVersion]
extended = true

[[module.mounts]]
source = "assets"
target = "assets"

[build]
writeStats = true

[params]
[params.plugins]
[[params.plugins.css]]
URL = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"

[[params.plugins.scss]]
URL = "scss/adritian.scss" 